#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// FORWARD DECLARATIONS


namespace ANIMBP_NVG { struct FAnimBlueprintGeneratedConstantData; }

namespace ANIMBP_Stinger_V2 { struct FAnimBlueprintGeneratedConstantData; }

namespace ANIMBP_CSGAS_V2 { struct FAnimBlueprintGeneratedConstantData; }

namespace ANIMBP_C2_Charge { struct FAnimBlueprintGeneratedConstantData; }

namespace ANIMBP_TacPhone { struct FAnimBlueprintGeneratedConstantData; }

namespace ReadyOrNot { struct FLoadoutCategory; }

namespace ANIMBP_Zipcuffs_Placed { struct FAnimBlueprintGeneratedConstantData; }

namespace W_FPSCounter { class UW_FPSCounter_C; }

namespace ANIMBP_Zipcuffs_Placed_FP { struct FAnimBlueprintGeneratedConstantData; }

namespace ANIMBP_Flashbang_V2 { struct FAnimBlueprintGeneratedConstantData; }

namespace W_FPSCounter_0 { class UW_FPSCounter_C; }

namespace ANIMBP_C2_Clacker { struct FAnimBlueprintGeneratedConstantData; }

namespace LoadoutCategory { struct FLoadoutCategory; }

namespace ANIMBP_Chemlight { struct FAnimBlueprintGeneratedConstantData; }

namespace ANIMBP_Zipcuffs { struct FAnimBlueprintGeneratedConstantData; }

namespace ABP_WP_PIS_TRP { struct FAnimBlueprintGeneratedConstantData; }


namespace ANIMBP_AI_MoveStyle_Base_V2
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_VKS
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_Player_FP_Master
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_MP510
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_Player_TP_V4
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_Head_Shared_Master
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_Head_Smudge
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_W870LL
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_G36C_V2
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_Multitool
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_Player_TP_V3
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_G19G5
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_MK18
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_M320
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_Fiveseven
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}

namespace ANIMBP_Python
{
	struct FAnimBlueprintGeneratedMutableData;
	struct FAnimBlueprintGeneratedConstantData;
}

namespace ANIMBP_BRN180
{
	struct FAnimBlueprintGeneratedConstantData;
	struct FAnimBlueprintGeneratedMutableData;
}
